name: First Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]
    

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      run: echo "Log from step one"
    - name: Step two
      run: echo "Log from step two"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Cowsays
      # You may pin to the exact commit or the version.
      # uses: mscoutermarsh/cowsays-action@822c8424f7ebc1f4c8b86b0bcb11e4051b7f42e2
      uses: mscoutermarsh/cowsays-action@v1
      with:
        text: "Ready for prod--ship it"
        color: "magenta"
          
    
